### ISSUE TITLE
[MAJOR] Rework

### ISSUE THREAD

**Issue by abebeos** [abebeos/SearchSECOController#1]
(draft)

# Proof of Concept => Product

This major issue/task affects several existent issues, and spawns several new issues. The goal is to rework the overall SearchSECOController project in a way that existent sporadic/hidden bugs are fixed, and future bugs of this kind happen less and/or can be fixed easier.

**Code-Quality** is increased mainly by strict refactoring (which does not affect functionality in any way, at least in theory).

**Project-Resources** (Tools and Processes) are transformed in a way to become more standard, thus developers can enter the project barrier-free.   

The work is executed mainly by one person.

## Duration

Assuming availability of budgets, many of the work can be done within the next 2 weeks (I am available to work in a "burst-mode" on this, meaning more than full-time).

## Tasks

- [x] #40 - accept reality first: things are bad
- [ ] #39 - very basic dev-system validation
- [ ] #36 - Fix one bug to get a sense of effort/situation
  - [ ] #43
    - [ ] https://github.com/SecureSECO/SearchSECOSpider/issues/17
- [ ] #45 (pick latest stable from #39)
- [ ] increase determinism of build/test (both locally and remote)
- [ ] Increase quality of project resources (github issues etc.) - imperative (use tools as supposed, follow standard-procedure)
- [ ] Increase general code-quality, mainly by strict refactoring - imperative (clean code reduces bugs, allows fast contributions)
- [ ] plan and execute updates to newer version (libraries)
- [ ] fix existing bugs (some are processed earlier during the steps above)
- [ ] => enhancements can continue here, revise descriptions.
- [ ] ...

## Bug Issues

Bugs are fixed either directly, or indirectly by the ongoing rework.

- [ ] #37
- [ ] #35 
- [ ] #31 
- [ ] #25
- [ ] #22
- [ ] #18 (if in context of Controller)

## Functionality Issues

(those should be implemented after the rework / bug-fixes)

- [ ] #23
- [ ] #27 
- [ ] #26
- [ ] #24
- [ ] https://github.com/SecureSECO/SearchSECOParser/issues/5
